"""empty message

Revision ID: ccdcfc913716
Revises: 
Create Date: 2020-01-22 00:04:02.855254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdcfc913716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('last_updated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firstname'), 'user', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_last_updated_time'), 'user', ['last_updated_time'], unique=False)
    op.create_index(op.f('ix_user_lastname'), 'user', ['lastname'], unique=False)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=120), nullable=False),
    sa.Column('rsvp_close_date', sa.Date(), nullable=False),
    sa.Column('reveal_date', sa.Date(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('host_join', sa.Boolean(), nullable=True),
    sa.Column('last_updated_time', sa.DateTime(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_budget'), 'group', ['budget'], unique=False)
    op.create_index(op.f('ix_group_groupname'), 'group', ['groupname'], unique=True)
    op.create_index(op.f('ix_group_host_join'), 'group', ['host_join'], unique=False)
    op.create_index(op.f('ix_group_last_updated_time'), 'group', ['last_updated_time'], unique=False)
    op.create_index(op.f('ix_group_reveal_date'), 'group', ['reveal_date'], unique=False)
    op.create_index(op.f('ix_group_rsvp_close_date'), 'group', ['rsvp_close_date'], unique=False)
    op.create_table('group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_member_member_email'), 'group_member', ['member_email'], unique=False)
    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('first_preference', sa.String(length=500), nullable=True),
    sa.Column('second_preference', sa.String(length=500), nullable=True),
    sa.Column('third_preference', sa.String(length=500), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_updated_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preference_first_preference'), 'preference', ['first_preference'], unique=False)
    op.create_index(op.f('ix_preference_last_updated_time'), 'preference', ['last_updated_time'], unique=False)
    op.create_index(op.f('ix_preference_second_preference'), 'preference', ['second_preference'], unique=False)
    op.create_index(op.f('ix_preference_third_preference'), 'preference', ['third_preference'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_third_preference'), table_name='preference')
    op.drop_index(op.f('ix_preference_second_preference'), table_name='preference')
    op.drop_index(op.f('ix_preference_last_updated_time'), table_name='preference')
    op.drop_index(op.f('ix_preference_first_preference'), table_name='preference')
    op.drop_table('preference')
    op.drop_index(op.f('ix_group_member_member_email'), table_name='group_member')
    op.drop_table('group_member')
    op.drop_index(op.f('ix_group_rsvp_close_date'), table_name='group')
    op.drop_index(op.f('ix_group_reveal_date'), table_name='group')
    op.drop_index(op.f('ix_group_last_updated_time'), table_name='group')
    op.drop_index(op.f('ix_group_host_join'), table_name='group')
    op.drop_index(op.f('ix_group_groupname'), table_name='group')
    op.drop_index(op.f('ix_group_budget'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_lastname'), table_name='user')
    op.drop_index(op.f('ix_user_last_updated_time'), table_name='user')
    op.drop_index(op.f('ix_user_firstname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
